"""second Migration

Revision ID: 520ab6c672a7
Revises: 
Create Date: 2019-10-24 10:15:29.689317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520ab6c672a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'id_user')
    # ### end Alembic commands ###
